# Nome do seu robô (workflow)
name: Run Python Script

# 1. O GATILHO: Quando o robô deve agir?
# Neste caso, sempre que houver um 'push' (envio de código) para a branch 'main'.
on:
  push:
    branches: [ "main" ]

# 2. O TRABALHO: O que o robô deve fazer?
jobs:
  # Nome do trabalho (pode ser qualquer nome)
  build:
    # O tipo de computador virtual que o robô usará
    runs-on: ubuntu-latest

    # 3. OS PASSOS: A sequência de comandos a executar
    steps:
      # Passo 1: Baixar o seu código para o computador virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configurar o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Você pode escolher a versão do Python

      # Passo 3: Instalar as bibliotecas do requirements.txt
      # ESTE É O PASSO MAIS IMPORTANTE PARA VOCÊ
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executar o seu script Python
      # TROQUE 'app.py' PELO NOME DO SEU ARQUIVO PYTHON
      - name: Run script
        run: python app.py
